version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform

  build:
    commands:
      - echo "Terraform version:"
      - terraform version

      - echo "Validating Terraform bootstrap..."
      - cd terraform/bootstrap
      - terraform init -backend=false
      - terraform validate

      - echo "Initializing Terraform dev environment with remote state..."
      - cd ../environments/dev
      - terraform init
      - terraform validate
      - terraform plan -out=tfplan

      - echo "Terraform validation and planning completed."