version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform

  build:
    commands:
      - echo "Terraform version:"
      - terraform version
      - echo "Starting Terraform validation..."
      - cd terraform/environments/dev
      - terraform init -backend=false
      - terraform validate
      - echo "Terraform validation completed."