services:
  minio:
    image: quay.io/minio/aistor/minio:RELEASE.2026-09-19T17-05-25Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: